/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CS5103;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.util.HashMap;
import java.util.Map;

import static junit.framework.Assert.assertTrue;
import static junit.framework.TestCase.assertEquals;

public class WordCounterTest {
    private WordCounter wordCounter;

    @Before
    public void setup() {
        wordCounter = new WordCounter();
    }

    @Test
    public void testBasic() {
        String input = "the word and the sentence and the line";
        Map<String, Integer> actualCounts = wordCounter.getWordCounts(input);

        // expected - [the - 3, and - 2, sentence - 1, line - 1, word - 1]
        Map<String, Integer> expectedCounts = new HashMap<>();
        expectedCounts.put("the", 3);
        expectedCounts.put("and", 2);
        expectedCounts.put("sentence", 1);
        expectedCounts.put("line", 1);
        expectedCounts.put("word", 1);

        assertEquals(expectedCounts, actualCounts);

        // now that we have removed one pair, the maps should not match
        expectedCounts.remove("word");
        Assert.assertNotEquals(expectedCounts, actualCounts);
    }

    @Test
    public void testEmptyInput() {
        String input = "";
        Map<String, Integer> wordCounts = wordCounter.getWordCounts(input);
        assertTrue(wordCounts.isEmpty());

        input = null;
        wordCounts = wordCounter.getWordCounts(input);
        assertTrue(wordCounts.isEmpty());
    }

    @Test
    public void testInputWithMultipleSpaces() {
        String input = "hello      there   how   are   you hello again";
        Map<String, Integer> wordCounts = wordCounter.getWordCounts(input);
        assertEquals(6, wordCounts.size());
        assertEquals(2, (int) wordCounts.get("hello"));
    }
}
